# Generated by Django 4.0 on 2024-06-05 06:32

from django.db import migrations, models
import musicplayer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='歌曲名')),
                ('file', models.FileField(null=True, upload_to=musicplayer.models.directory_path, verbose_name='文件')),
            ],
            options={
                'verbose_name_plural': '音乐',
            },
        ),
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='歌单名')),
                ('cover', models.ImageField(blank=True, upload_to=musicplayer.models.directory_path, verbose_name='图片')),
                ('mtype', models.PositiveSmallIntegerField(choices=[(0, '愤怒'), (1, '快乐'), (2, '伤感'), (3, '兴奋'), (4, '安静')], default=1, verbose_name='情绪类型')),
                ('music', models.ManyToManyField(blank=True, related_name='musics', to='musicplayer.Music', verbose_name='歌曲')),
            ],
            options={
                'verbose_name_plural': '歌单',
                'ordering': ['id'],
            },
        ),
    ]
