# Generated by Django 4.0 on 2024-06-05 06:32

from django.db import migrations, models
import faceemotion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='标题')),
                ('image', models.ImageField(blank=True, upload_to=faceemotion.models.path_and_rename, verbose_name='图片')),
            ],
        ),
    ]
